// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XV_NhwyfokQN7ZTrx4KDi8L2QZTPYfA',
    appId: '1:1035319385619:web:e4939e2c49ae797a60e9e6',
    messagingSenderId: '1035319385619',
    projectId: 'ysyw-01',
    authDomain: 'ysyw-01.firebaseapp.com',
    storageBucket: 'ysyw-01.firebasestorage.app',
    measurementId: 'G-LK15ZE32XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKI8J9pmqeKEmozTdsitEcIQ0af8PbTY',
    appId: '1:1035319385619:android:b5583ea20af93d4b60e9e6',
    messagingSenderId: '1035319385619',
    projectId: 'ysyw-01',
    storageBucket: 'ysyw-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcgygWlVOncC3R7yykF6oF4EQOCyMjhzk',
    appId: '1:1035319385619:ios:d0051400121e304960e9e6',
    messagingSenderId: '1035319385619',
    projectId: 'ysyw-01',
    storageBucket: 'ysyw-01.firebasestorage.app',
    iosBundleId: 'com.yoursportyourworld.ysyw',
  );
}
